#sudo: required	
dist: precise

addons:
  apt:
    packages:
    - libboost-dev
    - libmbedtls-dev
    - libmbedcrypto0

language: cpp
compiler:
  - gcc
  - clang

script: mkdir -p build && cd build && cmake .. && make
